### ISSUE TITLE
Joint Learning of Answer Selection and Answer Summary Generation in Community Question Answering 论文中公式维度疑问

### ISSUE THREAD

**Issue by chenjun0210** [dengyang17/wikihowQA#1]
![image](https://user-images.githubusercontent.com/8360385/103144842-3f0fb980-476b-11eb-94ec-6b8c6ce3dd17.png)

请问一下大佬，这里面几个公式中对应的问题，answer矩阵shape分别是多少呀？以及得到最终表示rq，ra的维度和表示？

**Comment by dengyang17** [comment]
M_{qa} \in R^{L_q x L_a}, \alpha_q \in R^{L_q},  \alpha_a \in R^{L_a}, r_q \in R^{d_s}, r_a \in R^{d_s},

**Comment by chenjun0210** [comment]
好的谢谢
